name: football_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  get: ^4.6.1
  snippet_coder_utils: ^1.0.8

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  json_table: ^2.0.1 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  delete_un_used_assets: ^1.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
